/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CalculatriceRouteImport } from './routes/calculatrice'
import { Route as AppRouteImport } from './routes/app'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppMeRouteImport } from './routes/app.me'
import { Route as AppLeaveRouteImport } from './routes/app.leave'
import { Route as AppDeclarationsRouteImport } from './routes/app.declarations'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAnnouncementsRouteImport } from './routes/app.announcements'
import { Route as AppAdvancesRouteImport } from './routes/app.advances'
import { Route as AppPayrollIndexRouteImport } from './routes/app.payroll.index'
import { Route as AppEmployeesIndexRouteImport } from './routes/app.employees.index'
import { Route as AppEmployeesIdRouteImport } from './routes/app.employees.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppPayrollPayslipIdRouteImport } from './routes/app.payroll.payslip.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatriceRoute = CalculatriceRouteImport.update({
  id: '/calculatrice',
  path: '/calculatrice',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRoute = AppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppDeclarationsRoute = AppDeclarationsRouteImport.update({
  id: '/declarations',
  path: '/declarations',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvancesRoute = AppAdvancesRouteImport.update({
  id: '/advances',
  path: '/advances',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollIndexRoute = AppPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPayrollPayslipIdRoute = AppPayrollPayslipIdRouteImport.update({
  id: '/payroll/payslip/$id',
  path: '/payroll/payslip/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aide': typeof AideRoute
  '/app': typeof AppRouteWithChildren
  '/calculatrice': typeof CalculatriceRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/declarations': typeof AppDeclarationsRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/me': typeof AppMeRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/app/employees/': typeof AppEmployeesIndexRoute
  '/app/payroll/': typeof AppPayrollIndexRoute
  '/app/payroll/payslip/$id': typeof AppPayrollPayslipIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aide': typeof AideRoute
  '/calculatrice': typeof CalculatriceRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/declarations': typeof AppDeclarationsRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/me': typeof AppMeRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/app/employees': typeof AppEmployeesIndexRoute
  '/app/payroll': typeof AppPayrollIndexRoute
  '/app/payroll/payslip/$id': typeof AppPayrollPayslipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aide': typeof AideRoute
  '/app': typeof AppRouteWithChildren
  '/calculatrice': typeof CalculatriceRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/declarations': typeof AppDeclarationsRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/me': typeof AppMeRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/app/employees/': typeof AppEmployeesIndexRoute
  '/app/payroll/': typeof AppPayrollIndexRoute
  '/app/payroll/payslip/$id': typeof AppPayrollPayslipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/aide'
    | '/app'
    | '/calculatrice'
    | '/cgv'
    | '/confidentialite'
    | '/login'
    | '/mentions-legales'
    | '/onboarding'
    | '/signup'
    | '/app/advances'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/declarations'
    | '/app/leave'
    | '/app/me'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/api/auth/$'
    | '/app/employees/$id'
    | '/app/employees/'
    | '/app/payroll/'
    | '/app/payroll/payslip/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/aide'
    | '/calculatrice'
    | '/cgv'
    | '/confidentialite'
    | '/login'
    | '/mentions-legales'
    | '/onboarding'
    | '/signup'
    | '/app/advances'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/declarations'
    | '/app/leave'
    | '/app/me'
    | '/app/reports'
    | '/app/settings'
    | '/app'
    | '/api/auth/$'
    | '/app/employees/$id'
    | '/app/employees'
    | '/app/payroll'
    | '/app/payroll/payslip/$id'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/aide'
    | '/app'
    | '/calculatrice'
    | '/cgv'
    | '/confidentialite'
    | '/login'
    | '/mentions-legales'
    | '/onboarding'
    | '/signup'
    | '/app/advances'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/declarations'
    | '/app/leave'
    | '/app/me'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/api/auth/$'
    | '/app/employees/$id'
    | '/app/employees/'
    | '/app/payroll/'
    | '/app/payroll/payslip/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AideRoute: typeof AideRoute
  AppRoute: typeof AppRouteWithChildren
  CalculatriceRoute: typeof CalculatriceRoute
  CgvRoute: typeof CgvRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculatrice': {
      id: '/calculatrice'
      path: '/calculatrice'
      fullPath: '/calculatrice'
      preLoaderRoute: typeof CalculatriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leave': {
      id: '/app/leave'
      path: '/leave'
      fullPath: '/app/leave'
      preLoaderRoute: typeof AppLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/declarations': {
      id: '/app/declarations'
      path: '/declarations'
      fullPath: '/app/declarations'
      preLoaderRoute: typeof AppDeclarationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advances': {
      id: '/app/advances'
      path: '/advances'
      fullPath: '/app/advances'
      preLoaderRoute: typeof AppAdvancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll/': {
      id: '/app/payroll/'
      path: '/payroll'
      fullPath: '/app/payroll/'
      preLoaderRoute: typeof AppPayrollIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees/': {
      id: '/app/employees/'
      path: '/employees'
      fullPath: '/app/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees/$id': {
      id: '/app/employees/$id'
      path: '/employees/$id'
      fullPath: '/app/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/payroll/payslip/$id': {
      id: '/app/payroll/payslip/$id'
      path: '/payroll/payslip/$id'
      fullPath: '/app/payroll/payslip/$id'
      preLoaderRoute: typeof AppPayrollPayslipIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdvancesRoute: typeof AppAdvancesRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppDeclarationsRoute: typeof AppDeclarationsRoute
  AppLeaveRoute: typeof AppLeaveRoute
  AppMeRoute: typeof AppMeRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
  AppPayrollIndexRoute: typeof AppPayrollIndexRoute
  AppPayrollPayslipIdRoute: typeof AppPayrollPayslipIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvancesRoute: AppAdvancesRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppDeclarationsRoute: AppDeclarationsRoute,
  AppLeaveRoute: AppLeaveRoute,
  AppMeRoute: AppMeRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppEmployeesIdRoute: AppEmployeesIdRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
  AppPayrollIndexRoute: AppPayrollIndexRoute,
  AppPayrollPayslipIdRoute: AppPayrollPayslipIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AideRoute: AideRoute,
  AppRoute: AppRouteWithChildren,
  CalculatriceRoute: CalculatriceRoute,
  CgvRoute: CgvRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
