/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppMeRouteImport } from './routes/app.me'
import { Route as AppLeaveRouteImport } from './routes/app.leave'
import { Route as AppDeclarationsRouteImport } from './routes/app.declarations'
import { Route as AppAdvancesRouteImport } from './routes/app.advances'
import { Route as AppPayrollIndexRouteImport } from './routes/app.payroll.index'
import { Route as AppEmployeesIndexRouteImport } from './routes/app.employees.index'
import { Route as AppEmployeesIdRouteImport } from './routes/app.employees.$id'
import { Route as AppPayrollPayslipIdRouteImport } from './routes/app.payroll.payslip.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRoute = AppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppDeclarationsRoute = AppDeclarationsRouteImport.update({
  id: '/declarations',
  path: '/declarations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvancesRoute = AppAdvancesRouteImport.update({
  id: '/advances',
  path: '/advances',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollIndexRoute = AppPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollPayslipIdRoute = AppPayrollPayslipIdRouteImport.update({
  id: '/payroll/payslip/$id',
  path: '/payroll/payslip/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/declarations': typeof AppDeclarationsRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/me': typeof AppMeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/app/employees/': typeof AppEmployeesIndexRoute
  '/app/payroll/': typeof AppPayrollIndexRoute
  '/app/payroll/payslip/$id': typeof AppPayrollPayslipIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/declarations': typeof AppDeclarationsRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/me': typeof AppMeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/app/employees': typeof AppEmployeesIndexRoute
  '/app/payroll': typeof AppPayrollIndexRoute
  '/app/payroll/payslip/$id': typeof AppPayrollPayslipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/declarations': typeof AppDeclarationsRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/me': typeof AppMeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/app/employees/': typeof AppEmployeesIndexRoute
  '/app/payroll/': typeof AppPayrollIndexRoute
  '/app/payroll/payslip/$id': typeof AppPayrollPayslipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/advances'
    | '/app/declarations'
    | '/app/leave'
    | '/app/me'
    | '/app/settings'
    | '/app/'
    | '/app/employees/$id'
    | '/app/employees/'
    | '/app/payroll/'
    | '/app/payroll/payslip/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/advances'
    | '/app/declarations'
    | '/app/leave'
    | '/app/me'
    | '/app/settings'
    | '/app'
    | '/app/employees/$id'
    | '/app/employees'
    | '/app/payroll'
    | '/app/payroll/payslip/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/advances'
    | '/app/declarations'
    | '/app/leave'
    | '/app/me'
    | '/app/settings'
    | '/app/'
    | '/app/employees/$id'
    | '/app/employees/'
    | '/app/payroll/'
    | '/app/payroll/payslip/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leave': {
      id: '/app/leave'
      path: '/leave'
      fullPath: '/app/leave'
      preLoaderRoute: typeof AppLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/declarations': {
      id: '/app/declarations'
      path: '/declarations'
      fullPath: '/app/declarations'
      preLoaderRoute: typeof AppDeclarationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advances': {
      id: '/app/advances'
      path: '/advances'
      fullPath: '/app/advances'
      preLoaderRoute: typeof AppAdvancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll/': {
      id: '/app/payroll/'
      path: '/payroll'
      fullPath: '/app/payroll/'
      preLoaderRoute: typeof AppPayrollIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees/': {
      id: '/app/employees/'
      path: '/employees'
      fullPath: '/app/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees/$id': {
      id: '/app/employees/$id'
      path: '/employees/$id'
      fullPath: '/app/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll/payslip/$id': {
      id: '/app/payroll/payslip/$id'
      path: '/payroll/payslip/$id'
      fullPath: '/app/payroll/payslip/$id'
      preLoaderRoute: typeof AppPayrollPayslipIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdvancesRoute: typeof AppAdvancesRoute
  AppDeclarationsRoute: typeof AppDeclarationsRoute
  AppLeaveRoute: typeof AppLeaveRoute
  AppMeRoute: typeof AppMeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
  AppPayrollIndexRoute: typeof AppPayrollIndexRoute
  AppPayrollPayslipIdRoute: typeof AppPayrollPayslipIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvancesRoute: AppAdvancesRoute,
  AppDeclarationsRoute: AppDeclarationsRoute,
  AppLeaveRoute: AppLeaveRoute,
  AppMeRoute: AppMeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppEmployeesIdRoute: AppEmployeesIdRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
  AppPayrollIndexRoute: AppPayrollIndexRoute,
  AppPayrollPayslipIdRoute: AppPayrollPayslipIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
